FROM node:20.9.0

ARG NEXT_PUBLIC_GRAPHQL_API
ENV NEXT_PUBLIC_GRAPHQL_API=${NEXT_PUBLIC_GRAPHQL_API}

WORKDIR /usr/aws-cloud-apps/ui

COPY ./package.json ./

RUN npm install --omit=dev

COPY . ./

## WAIT mod
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait
RUN chmod +x /wait