version: '3'
services:
  postgres:
    container_name: postgres_dev
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  api:
    container_name: api_dev
    working_dir: /usr/aws-cloud-apps/graphql
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - WAIT_HOSTS=postgres:5432
    ports:
      - "4000:4000"
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:/usr/aws-cloud-apps/graphql
      - /usr/aws-cloud-apps/graphql/node_modules
    command: |
      sh -c "/wait && npm run dev"
  client:
    container_name: client_dev
    working_dir: /usr/aws-cloud-apps/client
    environment:
      # TODO - using localhost instead of api as a host name because of a bug in docker-compose
      - NEXT_PUBLIC_GRAPHQL_API=http://localhost:4000/graphql
      - WAIT_HOSTS=api:4000
    ports:
      - "3000:3000"
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/usr/aws-cloud-apps/client
      - /usr/aws-cloud-apps/client/node_modules
    command: |
      sh -c "/wait && npm run dev"
