version: '3'
services:
  postgres:
    container_name: postgres_dev
    build:
      context: ./server/postgres
    ports:
      - "5432:5432"
    # TODO - replace this by creating a default superadmin with SQL for phase 4
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  api:
    container_name: api_dev
    working_dir: /usr/cloud-apps/api
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
      - WAIT_HOSTS=postgres:5432
    ports:
      - "4000:4000"
    build:
      context: ./server/api
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ./server/api:/usr/cloud-apps/api
      - /usr/cloud-apps/api/node_modules
    command: |
      sh -c "/wait && npm run dev"
  ui:
    container_name: ui_dev
    working_dir: /usr/cloud-apps/ui_outdated
    environment:
      - WAIT_HOSTS=api:4000
    ports:
      - "3000:3000"
    build:
      context: client/ui_outdated
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ./client/ui_outdated:/usr/cloud-apps/ui_outdated
      - /usr/cloud-apps/ui_outdated/node_modules
    command: |
      sh -c "/wait && npm run dev"
