version: '3'
services:
  # uses init.sql to populate schema instead of migrations to improve e2e test build time
  ## in production versions, init.sql usage should be avoided and instead populate schema with migrations to be consistent with rest of ci/cd
  postgres:
    container_name: postgres_e2e_tests
    build:
      context: ./server/postgres
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  api:
    container_name: api_e2e_tests
    working_dir: /usr/cloud-apps/graphql
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - WAIT_HOSTS=postgres:5432
    ports:
      - "4000:4000"
    build:
      context: ./server/graphql
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ./server/graphql:/usr/cloud-apps/graphql
      - /usr/cloud-apps/graphql/node_modules
    command: |
      sh -c "/wait && npm run dev"
  ui:
    container_name: ui_e2e_tests
    working_dir: /usr/cloud-apps/ui
    environment:
      - NEXT_PUBLIC_GRAPHQL_API=http://api:4000/graphql
      - WAIT_HOSTS=api:4000
    ports:
      - "3000:3000"
    build:
      context: client/ui
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ./client/ui:/usr/cloud-apps/ui
      - /usr/cloud-apps/ui/node_modules
    command: |
      sh -c "/wait && npm run dev"
  e2e:
    container_name: e2e_tests
    working_dir: /usr/cloud-apps/e2e
    environment:
      - UI=http://ui:3000
      - WAIT_HOSTS=ui:3000
    build:
      context: client/playwright
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ./client/playwright/test-results:/usr/cloud-apps/e2e/test-results
      - ./client/playwright:/usr/cloud-apps/e2e
      - /usr/cloud-apps/e2e/node_modules
    command: |
      sh -c "/wait && npx playwright test"
networks:
  nightwatch-docker-grid-network:
    driver: bridge