version: '3'
services:
  postgres:
    container_name: postgres_tests
    build:
      context: ./server/postgres
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  api:
    container_name: api_tests
    working_dir: /usr/cloud-apps/graphql
    environment:
      - DB_USER=postgres
      - DB_HOST=postgres
      - DB_NAME=postgres
      - DB_PORT=5432
      - DB_PASSWORD=postgres_password
      - WAIT_HOSTS=postgres:5432
    ports:
      - "4000:4000"
    build:
      context: ./server/graphql
      dockerfile: docker/Dockerfile.dev
    command: |
      sh -c "/wait && npm run dev"
  integration:
    container_name: integration_tests
    working_dir: /usr/cloud-apps/integration-tests
    environment:
      - API=http://api:4000
      - WAIT_HOSTS=api:4000
    build:
      context: ./server/tests
      dockerfile: docker/Dockerfile
    command: |
      sh -c "/wait && npm start"
