version: '3'
services:
  postgres:
    container_name: postgres_prod
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  api:
    container_name: api_prod
    working_dir: /usr/aws-cloud-apps/graphql
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
    - "4000:4000"
    build:
      context: ./api
      dockerfile: Dockerfile
  ## there seems to be a bug with next.js and docker-compose here npm build & npm start is not defining environment variables
  client:
    container_name: client_prod
    working_dir: /usr/aws-cloud-apps/client
    env_file:
      - client/ui/.env
    environment:
      - NEXT_PUBLIC_GRAPHQL_API=http://localhost:4000/graphql
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"