docker_cimg: &docker_cimg
  docker:
    - image: cimg/python:3.9.1

version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@7.0.0
  aws-ecs: circleci/aws-ecs@2.0.0

parameters:
  is_pull_request:
    type: boolean
    default: false
  target_branch:
    type: string
    default: ""
workflows:
  automated-tests:
    unless:
      or:
        - equal: [ true, << pipeline.parameters.is_pull_request >> ]
        - equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - ui-unit-tests
  build-and-deploy-cloud-apps:
    when:
      or:
        - equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - build-and-push-ui-image:
          context: cloud-apps-2023
          name: 'build-and-push-ui-image'
      - build-and-push-api-image:
          context: cloud-apps-2023
          name: 'build-and-push-api-image'
jobs:
  ui-unit-tests:
    working_directory: ~/client/ui
    docker:
      - image: cimg/node:20.9.0 # lock in version of node to prevent dependency issues
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "client/ui/package.json" }}
      - run:
          name: "Install UI dev-only dependencies"
          command: "cd client/ui && npm i -D"
      - save_cache:
          key: dependency-cache-{{ checksum "client/ui/package.json" }}
          paths:
            - ./node_modules
      - run:
          name: "Run unit tests"
          command: "cd client/ui && npm run test:coverage"
  build-and-push-ui-image:
    <<: *docker_cimg
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          repo: 'cloud-apps-ui'
          path: './client/ui'
          dockerfile: 'docker/Dockerfile'
          tag: 'latest,v<< pipeline.number >>'
          extra-build-args: '--build-arg NEXT_PUBLIC_GRAPHQL_API'
      - aws-ecs/update-service:
          cluster-name: 'cloud-apps-2023'
          container-image-name-updates: 'container=latest,tag=latest'
          family: 'cloud-apps-ui'
          service-name: 'cloud-apps-ui'
  build-and-push-api-image:
    <<: *docker_cimg
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          repo: 'cloud-apps-api'
          path: './server/graphql'
          dockerfile: 'docker/Dockerfile'
          tag: 'latest,v<< pipeline.number >>'
          extra-build-args: '--build-arg DB_HOST --build-arg DB_PORT --build-arg DB_NAME --build-arg DB_USER --build-arg DB_PASSWORD'
      - aws-ecs/update-service:
          cluster-name: 'cloud-apps-2023'
          container-image-name-updates: 'container=latest,tag=latest'
          family: 'cloud-apps-api'
          service-name: 'cloud-apps-api'