FROM node:20.9.0

ARG DATABASE_URL

ENV DATABASE_URL=${DATABASE_URL}

WORKDIR /usr/postgres/migrations
COPY ./ ./

RUN npm install

## WAIT mod
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.10.0/wait /wait
RUN chmod +x /wait